services:
  app:
    build:
      context: ./docker/php
    image: laravel_app
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel
    # ports:
    #   - 8080:8080
    depends_on:
      couchbase:
        condition: service_healthy
      redis:
        condition: service_started

  web:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel
    depends_on:
      - app

  couchbase:
    build:
      context: ./docker/couchbase
    container_name: couchbase
    ports:
      - "8091-8096:8091-8096"
      - "11210-11211:11210-11211"
    expose: # expose ports 8091 & 8094 to other containers (mainly for backend)
      - "8091"
      - "8094"
    networks:
      - laravel
    environment:
      - COUCHBASE_HOST
      - COUCHBASE_CLUSTER
      - COUCHBASE_ADMINISTRATOR_USERNAME
      - COUCHBASE_ADMINISTRATOR_PASSWORD
      - COUCHBASE_BUCKET
      - COUCHBASE_USERNAME
      - COUCHBASE_PASSWORD
    healthcheck: # checks couchbase server is up
      test: ["CMD", "curl", "-v", "http://localhost:8091/pools"]
      interval: 5s
      timeout: 20s
      retries: 90

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge