services:
  app:
    build:
      context: ./docker/php
    image: laravel_app
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - couchbase
      - redis

  web:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel
    depends_on:
      - app

  couchbase:
    build:
      context: ./docker/couchbase
    container_name: couchbase
    ports:
      - "8091-8096:8091-8096"
      - "11210-11211:11210-11211"
    networks:
      - laravel
    environment:
      - COUCHBASE_CLUSTER
      - COUCHBASE_ADMINISTRATOR_USERNAME
      - COUCHBASE_ADMINISTRATOR_PASSWORD
      - COUCHBASE_BUCKET
      - COUCHBASE_USERNAME
      - COUCHBASE_PASSWORD

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge